# Site
name: "Omnia"
title: "Omnia"
description: "A blog for all things tech"
logo: 'assets/images/apple-touch-icon.png'
favicon: 'assets/images/favicon.ico'
disqus: "omnia-core"
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  kevin:
    name: Kevin
    display_name: Kevin
    gravatar: f1eea0082761fcd8e82ebd8aa6de5410
    email: kevinhwang1227@gmail.com
    web: https://omnia-core.github.io
    description: "Author of Omnia Blog."
    twitter: https://x.com/kevin_omnia

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "enabled"
adsense-data-ad-client: "ca-pub-1914240913191564"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, README.md, Gemfile, Gemfile.lock]
